# Package

In [1]:
# ! pip install cebra

import sys
import itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import random
import cebra
import cebra.datasets
from cebra import CEBRA
import cebra.grid_search
import time
import os
from collections import Counter

/work/09117/xz6783/ls6/Anaconda/envs/cebra-gpu/lib/python3.8/site-packages/cebra/datasets/__init__.py:92: UserWarning: Could not initialize one or more datasets: No module named 'h5py'. For using the datasets, consider installing the [datasets] extension via pip.
  warnings.warn(f"Could not initialize one or more datasets: {e}. "

In [2]:
conf_dir = "/scratch/09117/xz6783/Xu/PL_miniscope/PL/Analysis/Cat_Odor_Conflict/Conflict/extracted_data/Calcium"
source_dir = "/scratch/09117/xz6783/Xu/CEBRA/Cebra_behavior/Cat_odor_conflict/training/data"
output_dir = "/scratch/09117/xz6783/Xu/CEBRA/Cebra_behavior/Cat_odor_conflict/training/output"
animal_id = '6S5'

In [3]:
# def process_data(conf_dir, file_name):
#     # Read data file
#     Dta = pd.read_pickle(os.path.join(conf_dir, file_name))
    
#     # Bin the dataset to one-second bin
#     Bins = int(Dta.shape[1] / 20)  
#     Dta = Dta.groupby(pd.cut(Dta.columns, Bins), axis=1).mean() 
#     Dta.columns = np.arange(0, Bins)
    
#     # Identifying cue onset and offset
#     cue = Dta.loc["Tone active"]
#     cueonset = np.array(np.where(np.diff(np.concatenate(([0], cue > 0))) > 0)[0])
#     cueoffset = np.array(np.where(np.diff(np.concatenate(([0], cue > 0))) < 0)[0])

#     # Prepare data
#     Dt = Dta.T
#     Time = Dt.index.values.astype(int) + 1
#     Dt.reset_index(drop=True, inplace=True)
# #     Dt.columns = np.arange(0, Dt.shape[1])
# #     Dt = Dt.astype("int64")
#     Dt.insert(0, "Timepoint", Time)
#     Dt.replace([np.inf, -np.inf], np.nan, inplace=True)
#     Dt.dropna(axis=1, inplace=True)


#     # Reorder columns
#     cols = list(Dt.columns)
#     cols = cols[:1] + cols[-8:-2] + cols[1:-8]
#     Dt = Dt[cols]
#     Dt = Dt.rename(columns={Dt.columns[1]: 'Time', Dt.columns[2]: 'Speed'})

#     # Extract the column names you want to rename (from the 8th column onwards)
#     columns_to_rename = Dt.columns[7:]

#     # Create a mapping dictionary
#     rename_dict = {old_name: new_name for old_name, new_name in zip(columns_to_rename, range(len(columns_to_rename)))}

#     # Use rename() with the dictionary
#     Dt = Dt.rename(columns=rename_dict)

#     return Dt

In [4]:
# for i in os.listdir(conf_dir):
#     animal_id = i.split('.')[0]
#     csv_data = process_data(conf_dir, i)
#     csv_data.to_csv(os.path.join(source_dir,f"{animal_id}.csv"))

# 1. Dataset

In [5]:
Dt = pd.read_csv(os.path.join(source_dir, f'{animal_id}.csv'), index_col= 0)
# Split
Y = Dt.iloc[:, 0:7]
X = Dt.iloc[:, 7:]
# View data
Dt

,Timepoint,Time,Speed,Freezing,In Food Area,In Hidden Area,Bar Press active,0,1,2,...,45,46,47,48,49,50,51,52,53,54
0,1,0.471571,0.043922,0.0,1.0,0.0,0.0,0.000000,2.229020,538.784037,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2,1.507050,0.028749,0.0,0.3,0.0,0.0,0.000000,58.090664,609.487166,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,3,2.518950,0.005867,0.0,0.0,0.0,0.0,0.000000,105.283135,520.979290,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4,3.530100,0.028687,0.0,0.0,0.0,0.0,0.000000,74.564003,445.324258,...,0.000000,0.000000,0.000000,0.000000,6.173056,7.798964,0.000000,0.000000,0.000000,0.000000
4,5,4.543400,0.034519,0.0,0.0,0.0,0.0,0.000000,52.807989,380.655621,...,0.000000,0.000000,0.000000,0.000000,89.831693,13.194525,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743,1744,1765.366950,0.000993,0.0,0.0,1.0,0.0,52.345445,3.119889,389.498863,...,21.834558,316.673884,246.192091,9.940888,887.937274,128.382850,1015.100783,11.704314,3.390824,185.520561
1744,1745,1766.379200,0.004755,0.0,0.0,1.0,0.0,62.450194,2.209579,334.722486,...,18.096680,278.480839,477.335863,8.951365,758.795480,108.573152,954.307390,9.891796,2.586663,164.534420
1745,1746,1767.391750,0.001854,0.0,0.0,1.0,0.0,94.048594,1.564876,355.075969,...,14.998692,244.894138,1060.436974,8.060339,650.423331,127.669162,897.154853,8.359963,1.973215,141.247686
1746,1747,1768.404250,0.000300,0.0,0.0,1.0,0.0,152.743294,1.108282,342.144116,...,12.431052,215.358223,1302.103857,7.258006,586.700685,143.777429,843.425125,7.065348,1.505252,121.256748
1747,1748,1769.430333,0.001597,0.0,0.0,1.0,0.0,158.975065,0.617917,301.155887,...,7.994440,146.123252,1087.751291,5.031113,388.451555,97.219734,607.832040,4.624728,0.897892,80.502073

In [6]:
Y

,Timepoint,Time,Speed,Freezing,In Food Area,In Hidden Area,Bar Press active
0,1,0.471571,0.043922,0.0,1.0,0.0,0.0
1,2,1.507050,0.028749,0.0,0.3,0.0,0.0
2,3,2.518950,0.005867,0.0,0.0,0.0,0.0
3,4,3.530100,0.028687,0.0,0.0,0.0,0.0
4,5,4.543400,0.034519,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
1743,1744,1765.366950,0.000993,0.0,0.0,1.0,0.0
1744,1745,1766.379200,0.004755,0.0,0.0,1.0,0.0
1745,1746,1767.391750,0.001854,0.0,0.0,1.0,0.0
1746,1747,1768.404250,0.000300,0.0,0.0,1.0,0.0
1747,1748,1769.430333,0.001597,0.0,0.0,1.0,0.0

In [7]:
X

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,0.000000,2.229020,538.784037,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,58.090664,609.487166,0.000000,0.000000,0.000000,33.629820,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,105.283135,520.979290,0.000000,0.000000,0.000000,163.380981,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,74.564003,445.324258,0.000000,0.000000,0.000000,345.094863,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,6.173056,7.798964,0.000000,0.000000,0.000000,0.000000
4,0.000000,52.807989,380.655621,0.000000,0.000000,0.000000,272.007418,0.000000,0.570634,25.261623,...,0.000000,0.000000,0.000000,0.000000,89.831693,13.194525,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743,52.345445,3.119889,389.498863,66.462902,380.361186,358.054928,13.949268,181.617513,0.000005,621.928931,...,21.834558,316.673884,246.192091,9.940888,887.937274,128.382850,1015.100783,11.704314,3.390824,185.520561
1744,62.450194,2.209579,334.722486,64.904308,297.333775,399.233207,10.603820,165.425612,0.000004,626.456175,...,18.096680,278.480839,477.335863,8.951365,758.795480,108.573152,954.307390,9.891796,2.586663,164.534420
1745,94.048594,1.564876,355.075969,70.800571,481.518109,370.991111,8.060709,182.684644,0.000003,604.723866,...,14.998692,244.894138,1060.436974,8.060339,650.423331,127.669162,897.154853,8.359963,1.973215,141.247686
1746,152.743294,1.108282,342.144116,65.049129,457.888657,287.382131,6.127512,257.482436,0.000003,583.745468,...,12.431052,215.358223,1302.103857,7.258006,586.700685,143.777429,843.425125,7.065348,1.505252,121.256748
1747,158.975065,0.617917,301.155887,45.917652,279.260215,166.536603,3.643471,192.882072,0.000002,430.839845,...,7.994440,146.123252,1087.751291,5.031113,388.451555,97.219734,607.832040,4.624728,0.897892,80.502073

# 2. Model setup
## We only consider three combination of categorical outcomes in this demo
1. [Freezing, In Hidden Area] 
2. [In Food Area, Bar Press Active] 
3. [Freezing, In Hidden Area, In Food Area, Bar Press Active]

## (1). Hyperparameter space

In [8]:
distance = ['cosine']               
temperature_mode = ['auto']                     
time_offsets = [10]   
batch_size = [None]              
learning_rate = [0.0001, 0.001, 0.01, 0.1, 1]    
conditional = ['time_delta']                            
output_dimension = [2, 3, 5, 10, 15]       
num_hidden_units = [32, 50, 75]                 
max_iterations = [7500]                           


# Put into a matrix
Hyperparameter_Space = [(a,b,c,d,e,f,g,h,i) 
                        for a in distance 
                        for b in temperature_mode 
                        for c in time_offsets 
                        for d in batch_size 
                        for e in learning_rate 
                        for f in conditional 
                        for g in output_dimension
                        for h in num_hidden_units
                        for i in max_iterations]
Hyperparameter_Mat = pd.DataFrame(Hyperparameter_Space)
Hyperparameter_Mat.columns = ['distance', 'temperature_mode', 'time_offsets', 'batch_size', 
                              'learning_rate', 'conditional', 'output_dimension', 'num_hidden_units', 'max_iterations']
Hyperparameter_Mat

,distance,temperature_mode,time_offsets,batch_size,learning_rate,conditional,output_dimension,num_hidden_units,max_iterations
0,cosine,auto,10,None,0.0001,time_delta,2,32,7500
1,cosine,auto,10,None,0.0001,time_delta,2,50,7500
2,cosine,auto,10,None,0.0001,time_delta,2,75,7500
3,cosine,auto,10,None,0.0001,time_delta,3,32,7500
4,cosine,auto,10,None,0.0001,time_delta,3,50,7500
...,...,...,...,...,...,...,...,...,...
70,cosine,auto,10,None,1.0000,time_delta,10,50,7500
71,cosine,auto,10,None,1.0000,time_delta,10,75,7500
72,cosine,auto,10,None,1.0000,time_delta,15,32,7500
73,cosine,auto,10,None,1.0000,time_delta,15,50,7500
74,cosine,auto,10,None,1.0000,time_delta,15,75,7500

## (2). Training function

In [9]:
# Self define training function
def Self_CEBRA_Time_Training(Toy, X, y):
    # Timer
    start_time = time.time()

    # DataFrame for evaluation metrics
    Performance = pd.DataFrame([])
    InfoNCE = []
    
    n_comb = len(Toy)

    for i in range(0, n_comb):
        # Extract hyperparameter
        Hyper_i = Toy.iloc[i, :]
        Hyperpara = {'distance': Hyper_i['distance'], 
                     'temperature_mode': Hyper_i['temperature_mode'], 
                     'time_offsets': Hyper_i['time_offsets'], 
                     'batch_size': Hyper_i['batch_size'],       
                     'learning_rate': Hyper_i['learning_rate'], 
                     'conditional': Hyper_i['conditional'], 
                     'output_dimension': Hyper_i['output_dimension'], 
                     'num_hidden_units': Hyper_i['num_hidden_units'], 
                     'max_iterations': Hyper_i['max_iterations']}

        # Extract sub-hyperparameters
        cebra_behavior_model = CEBRA(batch_size = Hyperpara['batch_size'],
                                     learning_rate = Hyperpara['learning_rate'],
                                     temperature_mode = Hyperpara['temperature_mode'],
                                     output_dimension = Hyperpara['output_dimension'],
                                     max_iterations = Hyperpara['max_iterations'],
                                     distance = Hyperpara['distance'],
                                     conditional = Hyperpara['conditional'],
                                     time_offsets = Hyperpara['time_offsets'],
                                     device = 'cuda_if_available',
                                     verbose = True)
        
        # Model fitting
        cebra_behavior_model.fit(X, y)
        
        # Model loss function value
        InfoNCELoss = cebra_behavior_model.state_dict_['loss'][7499]
        InfoNCE.append(InfoNCELoss.tolist())

    print("--- %s seconds ---" % (time.time() - start_time))

    # Training performance
    dt = {'Accuracy_Testing': InfoNCE}
    Performance = pd.DataFrame(dt)

    # Combined train and test results
    Combined_Rsult = pd.concat([Toy, Performance], axis = 1)
    return(Combined_Rsult)

In [10]:
# Cut hyperparameter space into difference pieces: 5 pieces (0-4)
Hyp_Pieces = np.array_split(range(len(Hyperparameter_Mat)), 5)

## (3). Train test split

In [11]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2024)

# Sort dataset by row index
X_train = X_train.sort_index()
X_test = X_test.sort_index()
y_train = y_train.sort_index()
y_test = y_test.sort_index()

# 3. Model training for different outcome combination

## (1). [Freezing, In Hidden Area]

## (2). [In Food Area, Bar Press Active]

In [12]:
# Extract specific combination
y_train_Comb2 = y_train.iloc[:, [4, 6]].to_numpy()

In [ ]:
# Batch 2
Toy0 = Hyperparameter_Mat.iloc[Hyp_Pieces[2], :]
Toy0.reset_index(drop=True, inplace=True)
Result_0 = Self_CEBRA_Time_Training(Toy0, X_train, y_train_Comb2)
Result_0.to_csv(os.path.join(output_dir, f'CEBRA_Behavior Training Results 2 (Comb 2) {animal_id}.csv'))

pos:  0.3457 neg:  6.6483 total:  6.9940 temperature:  0.3482: 100%|██████████| 7500/7500 [03:41<00:00, 33.82it/s]
pos:  0.3681 neg:  6.6012 total:  6.9693 temperature:  0.3051: 100%|██████████| 7500/7500 [03:41<00:00, 33.85it/s]
pos:  0.4201 neg:  6.5847 total:  7.0047 temperature:  0.3006: 100%|██████████| 7500/7500 [03:30<00:00, 35.68it/s]
pos:  0.6528 neg:  6.2167 total:  6.8695 temperature:  0.1000: 100%|██████████| 7500/7500 [03:40<00:00, 34.07it/s]
pos:  0.6363 neg:  6.2136 total:  6.8498 temperature:  0.1000:  22%|██▏       | 1648/7500 [00:47<02:46, 35.05it/s]