# Package

In [1]:
# ! pip install cebra

import sys
import itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import random
import cebra
import cebra.datasets
from cebra import CEBRA
import cebra.grid_search
import time
import os
from collections import Counter

/work/09117/xz6783/ls6/Anaconda/envs/cebra-gpu/lib/python3.8/site-packages/cebra/datasets/__init__.py:92: UserWarning: Could not initialize one or more datasets: No module named 'h5py'. For using the datasets, consider installing the [datasets] extension via pip.
  warnings.warn(f"Could not initialize one or more datasets: {e}. "

In [2]:
conf_dir = "/scratch/09117/xz6783/Xu/PL_miniscope/PL/Analysis/Cat_Odor_Conflict/Conflict/extracted_data/Calcium"
source_dir = "/scratch/09117/xz6783/Xu/CEBRA/Cebra_behavior/Cat_odor_conflict/training/data"
output_dir = "/scratch/09117/xz6783/Xu/CEBRA/Cebra_behavior/Cat_odor_conflict/training/output"
animal_id = '6M6'

In [3]:
# def process_data(conf_dir, file_name):
#     # Read data file
#     Dta = pd.read_pickle(os.path.join(conf_dir, file_name))
    
#     # Bin the dataset to one-second bin
#     Bins = int(Dta.shape[1] / 20)  
#     Dta = Dta.groupby(pd.cut(Dta.columns, Bins), axis=1).mean() 
#     Dta.columns = np.arange(0, Bins)
    
#     # Identifying cue onset and offset
#     cue = Dta.loc["Tone active"]
#     cueonset = np.array(np.where(np.diff(np.concatenate(([0], cue > 0))) > 0)[0])
#     cueoffset = np.array(np.where(np.diff(np.concatenate(([0], cue > 0))) < 0)[0])

#     # Prepare data
#     Dt = Dta.T
#     Time = Dt.index.values.astype(int) + 1
#     Dt.reset_index(drop=True, inplace=True)
# #     Dt.columns = np.arange(0, Dt.shape[1])
# #     Dt = Dt.astype("int64")
#     Dt.insert(0, "Timepoint", Time)
#     Dt.replace([np.inf, -np.inf], np.nan, inplace=True)
#     Dt.dropna(axis=1, inplace=True)


#     # Reorder columns
#     cols = list(Dt.columns)
#     cols = cols[:1] + cols[-8:-2] + cols[1:-8]
#     Dt = Dt[cols]
#     Dt = Dt.rename(columns={Dt.columns[1]: 'Time', Dt.columns[2]: 'Speed'})

#     # Extract the column names you want to rename (from the 8th column onwards)
#     columns_to_rename = Dt.columns[7:]

#     # Create a mapping dictionary
#     rename_dict = {old_name: new_name for old_name, new_name in zip(columns_to_rename, range(len(columns_to_rename)))}

#     # Use rename() with the dictionary
#     Dt = Dt.rename(columns=rename_dict)

#     return Dt

In [4]:
# for i in os.listdir(conf_dir):
#     animal_id = i.split('.')[0]
#     csv_data = process_data(conf_dir, i)
#     csv_data.to_csv(os.path.join(source_dir,f"{animal_id}.csv"))

# 1. Dataset

In [5]:
Dt = pd.read_csv(os.path.join(source_dir, f'{animal_id}.csv'), index_col= 0)
# Split
Y = Dt.iloc[:, 0:7]
X = Dt.iloc[:, 7:]
# View data
Dt

,Timepoint,Time,Speed,Freezing,In Food Area,In Hidden Area,Bar Press active,0,1,2,...,128,129,130,131,132,133,134,135,136,137
0,1,0.499571,0.026190,0.0,0.0000,1.000000,0.00,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2,1.537900,0.041649,0.0,0.0000,1.000000,0.00,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,3,2.549300,0.129952,0.0,0.3675,0.007895,0.00,0.000000,0.000000,0.000000,...,3.193001,0.000000,0.000000,0.000000,6.400005,0.000000,0.000000,6.285662,0.000000,0.000000
3,4,3.560900,0.030860,0.0,1.0000,0.000000,0.30,0.000000,0.000000,0.000000,...,12.867394,0.000000,0.000000,5.576823,18.778582,0.000000,0.000000,6.815444,0.000000,0.000000
4,5,4.572900,0.019806,0.0,1.0000,0.000000,0.15,0.000000,0.000000,116.331466,...,11.290958,2.413726,3.899698,30.767781,18.299839,0.000000,0.000000,15.201510,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,1771,1792.454500,0.000000,1.0,0.0000,1.000000,0.00,0.707592,1.654004,172.566795,...,16.697797,21.406706,153.501237,65.351870,119.415868,72.117965,0.231196,84.197811,19.415544,39.634189
1771,1772,1792.579000,0.000000,1.0,0.0000,1.000000,0.00,0.606639,1.464108,173.853374,...,21.708866,22.528439,145.202108,60.353983,121.641317,69.993939,0.204435,81.513892,17.289795,36.186032
1772,1773,1792.579000,0.000000,1.0,0.0000,1.000000,0.00,0.520088,1.296013,162.067323,...,38.151781,20.261302,137.351676,55.839169,124.484340,67.932471,0.180771,86.218183,18.329636,33.037862
1773,1774,1792.579000,0.000000,1.0,0.0000,1.000000,0.00,0.445887,1.147218,147.636002,...,36.671196,18.222318,129.925681,60.831288,114.832183,65.931717,0.159847,82.789053,23.848226,30.163582
1774,1775,1792.579000,0.000000,1.0,0.0000,1.000000,0.00,0.380841,1.012478,134.181500,...,32.075833,16.345911,122.732138,58.379971,105.717851,63.942328,0.140919,78.919135,21.027441,27.477742

In [6]:
Y

,Timepoint,Time,Speed,Freezing,In Food Area,In Hidden Area,Bar Press active
0,1,0.499571,0.026190,0.0,0.0000,1.000000,0.00
1,2,1.537900,0.041649,0.0,0.0000,1.000000,0.00
2,3,2.549300,0.129952,0.0,0.3675,0.007895,0.00
3,4,3.560900,0.030860,0.0,1.0000,0.000000,0.30
4,5,4.572900,0.019806,0.0,1.0000,0.000000,0.15
...,...,...,...,...,...,...,...
1770,1771,1792.454500,0.000000,1.0,0.0000,1.000000,0.00
1771,1772,1792.579000,0.000000,1.0,0.0000,1.000000,0.00
1772,1773,1792.579000,0.000000,1.0,0.0000,1.000000,0.00
1773,1774,1792.579000,0.000000,1.0,0.0000,1.000000,0.00
1774,1775,1792.579000,0.000000,1.0,0.0000,1.000000,0.00

In [7]:
X

,0,1,2,3,4,5,6,7,8,9,...,128,129,130,131,132,133,134,135,136,137
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.539948,0.000000,0.000000,0.000000,0.542036,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,22.300369,0.000000,0.000000,3.092045,8.516805,5.556188,...,3.193001,0.000000,0.000000,0.000000,6.400005,0.000000,0.000000,6.285662,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,25.195590,4.958827,0.000000,6.645071,9.297426,19.923566,...,12.867394,0.000000,0.000000,5.576823,18.778582,0.000000,0.000000,6.815444,0.000000,0.000000
4,0.000000,0.000000,116.331466,70.755602,23.773180,37.129407,0.000000,7.467981,8.342649,18.132379,...,11.290958,2.413726,3.899698,30.767781,18.299839,0.000000,0.000000,15.201510,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,0.707592,1.654004,172.566795,14.281693,81.963048,37.115461,14.974377,8.167806,20.083272,48.998279,...,16.697797,21.406706,153.501237,65.351870,119.415868,72.117965,0.231196,84.197811,19.415544,39.634189
1771,0.606639,1.464108,173.853374,16.205629,87.206669,42.769176,13.615424,7.043091,19.328855,54.402581,...,21.708866,22.528439,145.202108,60.353983,121.641317,69.993939,0.204435,81.513892,17.289795,36.186032
1772,0.520088,1.296013,162.067323,18.758598,82.283440,38.731499,11.911210,6.073251,17.343925,49.467067,...,38.151781,20.261302,137.351676,55.839169,124.484340,67.932471,0.180771,86.218183,18.329636,33.037862
1773,0.445887,1.147218,147.636002,16.759730,77.638150,35.075004,10.420308,5.236958,18.633399,49.769683,...,36.671196,18.222318,129.925681,60.831288,114.832183,65.931717,0.159847,82.789053,23.848226,30.163582
1774,0.380841,1.012478,134.181500,14.932546,73.149817,31.686388,9.086289,4.499551,19.109177,45.908193,...,32.075833,16.345911,122.732138,58.379971,105.717851,63.942328,0.140919,78.919135,21.027441,27.477742

# 2. Model setup
## We only consider three combination of categorical outcomes in this demo
1. [Freezing, In Hidden Area] 
2. [In Food Area, Bar Press Active] 
3. [Freezing, In Hidden Area, In Food Area, Bar Press Active]

## (1). Hyperparameter space

In [8]:
distance = ['cosine']               
temperature_mode = ['auto']                     
time_offsets = [10]   
batch_size = [None]              
learning_rate = [0.0001, 0.001, 0.01, 0.1, 1]    
conditional = ['time_delta']                            
output_dimension = [2, 3, 5, 10, 15]       
num_hidden_units = [32, 50, 75]                 
max_iterations = [7500]                           


# Put into a matrix
Hyperparameter_Space = [(a,b,c,d,e,f,g,h,i) 
                        for a in distance 
                        for b in temperature_mode 
                        for c in time_offsets 
                        for d in batch_size 
                        for e in learning_rate 
                        for f in conditional 
                        for g in output_dimension
                        for h in num_hidden_units
                        for i in max_iterations]
Hyperparameter_Mat = pd.DataFrame(Hyperparameter_Space)
Hyperparameter_Mat.columns = ['distance', 'temperature_mode', 'time_offsets', 'batch_size', 
                              'learning_rate', 'conditional', 'output_dimension', 'num_hidden_units', 'max_iterations']
Hyperparameter_Mat

,distance,temperature_mode,time_offsets,batch_size,learning_rate,conditional,output_dimension,num_hidden_units,max_iterations
0,cosine,auto,10,None,0.0001,time_delta,2,32,7500
1,cosine,auto,10,None,0.0001,time_delta,2,50,7500
2,cosine,auto,10,None,0.0001,time_delta,2,75,7500
3,cosine,auto,10,None,0.0001,time_delta,3,32,7500
4,cosine,auto,10,None,0.0001,time_delta,3,50,7500
...,...,...,...,...,...,...,...,...,...
70,cosine,auto,10,None,1.0000,time_delta,10,50,7500
71,cosine,auto,10,None,1.0000,time_delta,10,75,7500
72,cosine,auto,10,None,1.0000,time_delta,15,32,7500
73,cosine,auto,10,None,1.0000,time_delta,15,50,7500
74,cosine,auto,10,None,1.0000,time_delta,15,75,7500

## (2). Training function

In [9]:
# Self define training function
def Self_CEBRA_Time_Training(Toy, X, y):
    # Timer
    start_time = time.time()

    # DataFrame for evaluation metrics
    Performance = pd.DataFrame([])
    InfoNCE = []
    
    n_comb = len(Toy)

    for i in range(0, n_comb):
        # Extract hyperparameter
        Hyper_i = Toy.iloc[i, :]
        Hyperpara = {'distance': Hyper_i['distance'], 
                     'temperature_mode': Hyper_i['temperature_mode'], 
                     'time_offsets': Hyper_i['time_offsets'], 
                     'batch_size': Hyper_i['batch_size'],       
                     'learning_rate': Hyper_i['learning_rate'], 
                     'conditional': Hyper_i['conditional'], 
                     'output_dimension': Hyper_i['output_dimension'], 
                     'num_hidden_units': Hyper_i['num_hidden_units'], 
                     'max_iterations': Hyper_i['max_iterations']}

        # Extract sub-hyperparameters
        cebra_behavior_model = CEBRA(batch_size = Hyperpara['batch_size'],
                                     learning_rate = Hyperpara['learning_rate'],
                                     temperature_mode = Hyperpara['temperature_mode'],
                                     output_dimension = Hyperpara['output_dimension'],
                                     max_iterations = Hyperpara['max_iterations'],
                                     distance = Hyperpara['distance'],
                                     conditional = Hyperpara['conditional'],
                                     time_offsets = Hyperpara['time_offsets'],
                                     device = 'cuda_if_available',
                                     verbose = True)
        
        # Model fitting
        cebra_behavior_model.fit(X, y)
        
        # Model loss function value
        InfoNCELoss = cebra_behavior_model.state_dict_['loss'][7499]
        InfoNCE.append(InfoNCELoss.tolist())

    print("--- %s seconds ---" % (time.time() - start_time))

    # Training performance
    dt = {'Accuracy_Testing': InfoNCE}
    Performance = pd.DataFrame(dt)

    # Combined train and test results
    Combined_Rsult = pd.concat([Toy, Performance], axis = 1)
    return(Combined_Rsult)

In [10]:
# Cut hyperparameter space into difference pieces: 5 pieces (0-4)
Hyp_Pieces = np.array_split(range(len(Hyperparameter_Mat)), 5)

## (3). Train test split

In [11]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2024)

# Sort dataset by row index
X_train = X_train.sort_index()
X_test = X_test.sort_index()
y_train = y_train.sort_index()
y_test = y_test.sort_index()

# 3. Model training for different outcome combination

## (1). [Freezing, In Hidden Area]

## (2). [In Food Area, Bar Press Active]

## (3). [Freezing, In Hidden Area, In Food Area, Bar Press Active]

In [12]:
# Extract specific combination
y_train_Comb3 = y_train.iloc[:, [3,4,5,6]].to_numpy()

In [13]:
# Batch 2
Toy0 = Hyperparameter_Mat.iloc[Hyp_Pieces[2], :]
Toy0.reset_index(drop=True, inplace=True)
Result_0 = Self_CEBRA_Time_Training(Toy0, X_train, y_train_Comb3)
Result_0.to_csv(os.path.join(output_dir, f'CEBRA_Behavior Training Results 2 (Comb 3) {animal_id}.csv'))

pos:  0.5455 neg:  6.1218 total:  6.6672 temperature:  0.4326: 100%|██████████| 7500/7500 [03:47<00:00, 32.93it/s]
pos:  0.4228 neg:  6.1557 total:  6.5785 temperature:  0.3863: 100%|██████████| 7500/7500 [03:39<00:00, 34.24it/s]
pos:  0.5003 neg:  6.1439 total:  6.6441 temperature:  0.4499: 100%|██████████| 7500/7500 [03:54<00:00, 31.95it/s]
pos:  0.7460 neg:  5.7228 total:  6.4688 temperature:  0.1343: 100%|██████████| 7500/7500 [04:00<00:00, 31.21it/s]
pos:  0.7699 neg:  5.7191 total:  6.4889 temperature:  0.1822:  16%|█▋        | 1223/7500 [00:38<03:22, 31.00it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

pos:  0.7931 neg:  5.7047 total:  6.4977 temperature:  0.1576:  48%|████▊     | 3612/7500 [01:52<01:58, 32.94it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

pos:  1.3307 neg:  4.9061 total:  6.2368 temperature:  0.1000:  75%|███████▌  | 5628/7500 [03:27<01:08, 27.27it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

pos:  1.3465 neg:  4.8757 total:  6.2223 temperature:  0.1000: 100%|██████████| 7500/7500 [04:31<00:00, 27.62it/s]
pos:  1.1132 neg:  5.0493 total:  6.1626 temperature:  0.1000: 100%|██████████| 7500/7500 [04:23<00:00, 28.42it/s]
pos:  2.0651 neg:  3.6940 total:  5.7591 temperature:  0.1000:  70%|███████   | 5279/7500 [03:15<01:20, 27.69it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

pos:  2.2448 neg:  3.5388 total:  5.7836 temperature:  0.1000:  74%|███████▍  | 5546/7500 [03:22<01:10, 27.80it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

pos:  2.1920 neg:  3.4985 total:  5.6905 temperature:  0.1000: 100%|██████████| 7500/7500 [04:35<00:00, 27.25it/s]
pos:  2.1148 neg:  3.7392 total:  5.8540 temperature:  0.1000:  46%|████▌     | 3417/7500 [02:11<02:42, 25.17it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

pos:  2.0913 neg:  3.7032 total:  5.7945 temperature:  0.1000: 100%|██████████| 7500/7500 [04:44<00:00, 26.37it/s]
pos:  2.4385 neg:  3.2160 total:  5.6544 temperature:  0.1000:  19%|█▉        | 1428/7500 [00:59<04:02, 25.03it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

pos:  2.3339 neg:  3.2127 total:  5.5466 temperature:  0.1000:  90%|█████████ | 6774/7500 [04:29<00:26, 27.02it/s]IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

pos:  2.4731 neg:  3.0868 total:  5.5599 temperature:  0.1000: 100%|██████████| 7500/7500 [04:57<00:00, 25.24it/s]
pos:  2.4055 neg:  3.1826 total:  5.5881 temperature:  0.1000: 100%|██████████| 7500/7500 [05:02<00:00, 24.81it/s]
pos:  2.3039 neg:  3.3581 total:  5.6620 temperature:  0.1000: 100%|██████████| 7500/7500 [04:42<00:00, 26.58it/s]

--- 3921.321310043335 seconds ---